//! Functional integration tests for SQLite.
//!
//! Assumes a pre-seeded `database.db` generated by Docker Compose
//! (`docker compose up sqlite`). The `DB_PATH` env var points to the database.
//!
//! ```bash
//! ./tests/run.sh --filter sqlite
//! ```

use backend::validation::validate_read_only_with_dialect;
use config::{DatabaseBackend, DatabaseConfig};
use rmcp::ServerHandler;
use sqlite::{SqliteBackend, SqliteHandler};

fn sqlite_config(db_path: &str, read_only: bool) -> DatabaseConfig {
    DatabaseConfig {
        backend: DatabaseBackend::Sqlite,
        port: 0,
        user: String::new(),
        name: Some(db_path.to_string()),
        read_only,
        ..DatabaseConfig::default()
    }
}

async fn backend() -> SqliteBackend {
    let db_path = std::env::var("DB_PATH").expect("DB_PATH must be set");
    let config = sqlite_config(&db_path, false);
    SqliteBackend::new(&config).await.expect("SQLite open failed")
}

async fn readonly_backend() -> SqliteBackend {
    let db_path = std::env::var("DB_PATH").expect("DB_PATH must be set");
    let config = sqlite_config(&db_path, true);
    SqliteBackend::new(&config).await.expect("SQLite open failed")
}

#[tokio::test]
async fn it_lists_tables() {
    let b = backend().await;
    let tables = b.list_tables("main").await.expect("failed");
    for expected in ["users", "posts", "tags", "post_tags"] {
        assert!(
            tables.iter().any(|t| t == expected),
            "Missing '{expected}' in: {tables:?}"
        );
    }
}

#[tokio::test]
async fn it_gets_table_schema() {
    let b = backend().await;
    let schema = b.get_table_schema("main", "users").await.expect("failed");
    let obj = schema.as_object().expect("object");
    assert!(obj.contains_key("table_name"), "Response should contain table_name");
    assert!(obj.contains_key("columns"), "Response should contain columns");
    let columns = obj["columns"].as_object().expect("columns object");
    for col in ["id", "name", "email", "created_at"] {
        assert!(columns.contains_key(col), "Missing '{col}' in: {columns:?}");
    }
}

#[tokio::test]
async fn it_gets_table_schema_with_relations() {
    let b = backend().await;
    let schema = b.get_table_schema("main", "posts").await.expect("failed");
    let columns = schema["columns"].as_object().expect("columns object");
    assert!(columns.contains_key("user_id"), "Missing 'user_id' column");
    let user_id = columns["user_id"].as_object().expect("user_id object");
    assert!(
        user_id.contains_key("foreign_key"),
        "Missing 'foreign_key' in user_id column"
    );
    assert!(
        !user_id["foreign_key"].is_null(),
        "foreign_key should not be null for user_id"
    );
}

#[tokio::test]
async fn it_executes_sql() {
    let b = backend().await;
    let results = b
        .execute_query("SELECT * FROM users ORDER BY id", Some("main"))
        .await
        .expect("failed");
    let rows = results.as_array().expect("array");
    assert_eq!(rows.len(), 3, "Expected 3 users, got {}", rows.len());
}

#[tokio::test]
async fn it_blocks_writes_in_read_only_mode() {
    let _b = readonly_backend().await;
    let dialect = sqlparser::dialect::SQLiteDialect {};
    let result = validate_read_only_with_dialect(
        "INSERT INTO users (name, email) VALUES ('Hacker', 'hack@evil.com')",
        &dialect,
    );
    assert!(result.is_err(), "Expected error for write in read-only mode");
}

#[tokio::test]
async fn it_preserves_json_types() {
    let b = backend().await;

    // COUNT(*) should return a JSON number, not a string or null
    let results = b
        .execute_query("SELECT COUNT(*) as cnt FROM users", Some("main"))
        .await
        .expect("failed");
    let rows = results.as_array().expect("array");
    let cnt = &rows[0]["cnt"];
    assert!(cnt.is_number(), "COUNT(*) should be a number, got: {cnt}");
    assert_eq!(cnt.as_i64(), Some(3), "Expected COUNT(*)=3");

    // Integer and text columns should have correct types
    let results = b
        .execute_query("SELECT id, name FROM users ORDER BY id LIMIT 1", Some("main"))
        .await
        .expect("failed");
    let rows = results.as_array().expect("array");
    assert!(
        rows[0]["id"].is_number(),
        "id should be a number, got: {}",
        rows[0]["id"]
    );
    assert!(
        rows[0]["name"].is_string(),
        "name should be a string, got: {}",
        rows[0]["name"]
    );
}

#[tokio::test]
async fn it_has_consistent_seed_data() {
    let b = backend().await;

    async fn check(b: &SqliteBackend, table: &str, expected: usize) {
        let sql = format!("SELECT CAST(COUNT(*) AS CHAR) as cnt FROM {table}");
        let results = b
            .execute_query(&sql, Some("main"))
            .await
            .unwrap_or_else(|e| panic!("count {table}: {e}"));
        let rows = results.as_array().expect("array");
        let count_str = rows[0]
            .get("cnt")
            .and_then(|v| v.as_str())
            .or_else(|| {
                rows[0]
                    .as_object()
                    .and_then(|o| o.values().next())
                    .and_then(|v| v.as_str())
            })
            .unwrap_or_else(|| panic!("No count for {table}: {:?}", rows[0]));
        let count: usize = count_str.parse().unwrap();
        assert_eq!(count, expected, "{table}: expected {expected}, got {count}");
    }

    check(&b, "users", 3).await;
    check(&b, "posts", 5).await;
    check(&b, "tags", 4).await;
    check(&b, "post_tags", 6).await;
}

#[tokio::test]
async fn it_excludes_list_databases_and_create_database_tools() {
    let db_path = std::env::var("DB_PATH").expect("DB_PATH must be set");
    let config = sqlite_config(&db_path, false);
    let handler = SqliteHandler::new(&config).await.expect("handler creation failed");

    assert!(
        handler.get_tool("list_databases").is_none(),
        "SQLite must not expose list_databases"
    );
    assert!(
        handler.get_tool("create_database").is_none(),
        "SQLite must not expose create_database"
    );

    // Verify core tools are present
    assert!(handler.get_tool("list_tables").is_some());
    assert!(handler.get_tool("read_query").is_some());
    assert!(handler.get_tool("write_query").is_some());
}
