//! Functional integration tests for SQLite.
//!
//! Assumes a pre-seeded `database.db` generated by Docker Compose
//! (`docker compose up sqlite`). The `DB_PATH` env var points to the database.
//!
//! ```bash
//! ./tests/run.sh --filter sqlite
//! ```

use sql_mcp::config::{DatabaseBackend, DatabaseConfig};
use sql_mcp::db::backend::Backend;
use sql_mcp::db::sqlite::SqliteBackend;

fn sqlite_config(db_path: &str, read_only: bool) -> DatabaseConfig {
    DatabaseConfig {
        backend: DatabaseBackend::Sqlite,
        port: 0,
        user: String::new(),
        name: Some(db_path.to_string()),
        read_only,
        ..DatabaseConfig::default()
    }
}

async fn backend() -> Backend {
    let db_path = std::env::var("DB_PATH").expect("DB_PATH must be set");
    let config = sqlite_config(&db_path, false);
    Backend::Sqlite(SqliteBackend::new(&config).await.expect("SQLite open failed"))
}

async fn readonly_backend() -> Backend {
    let db_path = std::env::var("DB_PATH").expect("DB_PATH must be set");
    let config = sqlite_config(&db_path, true);
    Backend::Sqlite(SqliteBackend::new(&config).await.expect("SQLite open failed"))
}

#[tokio::test]
async fn it_lists_databases() {
    let b = backend().await;
    let result = b.tool_list_databases().await.expect("failed");
    let dbs: Vec<String> = serde_json::from_str(&result).expect("bad json");
    assert!(dbs.iter().any(|db| db == "main"), "Expected 'main' in: {dbs:?}");
}

#[tokio::test]
async fn it_lists_tables() {
    let b = backend().await;
    let result = b.tool_list_tables("main").await.expect("failed");
    let tables: Vec<String> = serde_json::from_str(&result).expect("bad json");
    for expected in ["users", "posts", "tags", "post_tags"] {
        assert!(
            tables.iter().any(|t| t == expected),
            "Missing '{expected}' in: {tables:?}"
        );
    }
}

#[tokio::test]
async fn it_gets_table_schema() {
    let b = backend().await;
    let result = b.tool_get_table_schema("main", "users").await.expect("failed");
    let schema: serde_json::Value = serde_json::from_str(&result).expect("bad json");
    let columns: Vec<String> = schema.as_object().expect("object").keys().cloned().collect();
    for col in ["id", "name", "email", "created_at"] {
        assert!(columns.iter().any(|c| c == col), "Missing '{col}' in: {columns:?}");
    }
}

#[tokio::test]
async fn it_gets_table_relations() {
    let b = backend().await;
    let result = b
        .tool_get_table_schema_with_relations("main", "posts")
        .await
        .expect("failed");
    assert!(
        result.contains("user_id") || result.contains("users"),
        "Expected foreign key reference in: {result}"
    );
}

#[tokio::test]
async fn it_executes_sql() {
    let b = backend().await;
    let result = b
        .tool_execute_sql("SELECT * FROM users ORDER BY id", "main", None)
        .await
        .expect("failed");
    let rows: Vec<serde_json::Value> = serde_json::from_str(&result).expect("bad json");
    assert_eq!(rows.len(), 3, "Expected 3 users, got {}", rows.len());
}

#[tokio::test]
async fn it_blocks_writes_in_read_only_mode() {
    let b = readonly_backend().await;
    let result = b
        .tool_execute_sql(
            "INSERT INTO users (name, email) VALUES ('Hacker', 'hack@evil.com')",
            "main",
            None,
        )
        .await;
    assert!(result.is_err(), "Expected error for write in read-only mode");
}

#[tokio::test]
async fn it_preserves_json_types() {
    let b = backend().await;

    // COUNT(*) should return a JSON number, not a string or null
    let result = b
        .tool_execute_sql("SELECT COUNT(*) as cnt FROM users", "main", None)
        .await
        .expect("failed");
    let rows: Vec<serde_json::Value> = serde_json::from_str(&result).expect("bad json");
    let cnt = &rows[0]["cnt"];
    assert!(cnt.is_number(), "COUNT(*) should be a number, got: {cnt}");
    assert_eq!(cnt.as_i64(), Some(3), "Expected COUNT(*)=3");

    // Integer and text columns should have correct types
    let result = b
        .tool_execute_sql("SELECT id, name FROM users ORDER BY id LIMIT 1", "main", None)
        .await
        .expect("failed");
    let rows: Vec<serde_json::Value> = serde_json::from_str(&result).expect("bad json");
    assert!(
        rows[0]["id"].is_number(),
        "id should be a number, got: {}",
        rows[0]["id"]
    );
    assert!(
        rows[0]["name"].is_string(),
        "name should be a string, got: {}",
        rows[0]["name"]
    );
}

#[tokio::test]
async fn it_has_consistent_seed_data() {
    let b = backend().await;

    async fn check(b: &Backend, table: &str, expected: usize) {
        let sql = format!("SELECT CAST(COUNT(*) AS CHAR) as cnt FROM {table}");
        let result = b
            .tool_execute_sql(&sql, "main", None)
            .await
            .unwrap_or_else(|e| panic!("count {table}: {e}"));
        let rows: Vec<serde_json::Value> = serde_json::from_str(&result).unwrap();
        let count_str = rows[0]
            .get("cnt")
            .and_then(|v| v.as_str())
            .or_else(|| {
                rows[0]
                    .as_object()
                    .and_then(|o| o.values().next())
                    .and_then(|v| v.as_str())
            })
            .unwrap_or_else(|| panic!("No count for {table}: {:?}", rows[0]));
        let count: usize = count_str.parse().unwrap();
        assert_eq!(count, expected, "{table}: expected {expected}, got {count}");
    }

    check(&b, "users", 3).await;
    check(&b, "posts", 5).await;
    check(&b, "tags", 4).await;
    check(&b, "post_tags", 6).await;
}
